using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace MagicBuilder.CodeAnalysis.Analyzers;

[Generator]
internal class BuilderGenerator : IIncrementalGenerator
{
    private static readonly StringBuilderPool stringBuilderPool = new();

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (ctx, compilation) =>
        {
            var attributeDatas = compilation.Assembly
                .GetAttributes()
                .Where(static attribute => attribute.AttributeClass?.Name.Equals(nameof(GenerateBuilderAttribute)) is true)
                .Select(static attribute => attribute.ConstructorArguments.First().Value)
                .Cast<ITypeSymbol>()
                .ToImmutableHashSet<ITypeSymbol>(SymbolEqualityComparer.Default);

            var sources = GenerateBuilderSourceGenerated(attributeDatas);

            foreach (var source in sources)
            {
                ctx.AddSource(source.Key, SourceText.From(source.Value, Encoding.UTF8));
            }
        });
    }

    private static IEnumerable<KeyValuePair<string, string>> GenerateBuilderSourceGenerated(ImmutableHashSet<ITypeSymbol> types)
    {
        foreach (var type in types)
        {
            yield return GenerateBuilderSourceGenerated(type, types);
        }
    }

    private static KeyValuePair<string, string> GenerateBuilderSourceGenerated(ITypeSymbol type, ImmutableHashSet<ITypeSymbol> types)
    {
        string typeName = type.Name;
        string namespaceName = type.ContainingNamespace.ToDisplayString();
        bool isGlobalNamespace = type.ContainingNamespace.IsGlobalNamespace;

        var members = type.GetMembers()
            .Where(s => s.CanBeReferencedByName && s.DeclaredAccessibility is Accessibility.Public)
            .OfType<IPropertySymbol>()
            .Where(p => p.SetMethod is not null);

        var @base = type.BaseType;

        while (@base != null)
        {
            members = members.Concat(@base.GetMembers()
                .Where(s => s.CanBeReferencedByName && s.DeclaredAccessibility is Accessibility.Public)
                .OfType<IPropertySymbol>()
                .Where(p => p.SetMethod is not null));

            @base = @base.BaseType;
        }


        var stringBuilder = stringBuilderPool.Rent();
        try
        {
            stringBuilder.AppendLine("""
                             // <auto-generated/>
                             using System;
                             """);

            if (!isGlobalNamespace)
            {
                stringBuilder.Append("using ")
                             .Append(namespaceName)
                             .AppendLine(";");
            }

            stringBuilder.Append("""
                                 namespace MagicBuilder {
                                     public static class 
                                 """)
                         .Append(typeName)
                         .Append("BuilderExtensions")
                         .AppendLine("""
                                 {
                                 """);

            foreach (var property in members)
            {
                GenerateBuilderMethod(type, types, property, stringBuilder);
            }

            stringBuilder.Append("""
                                 }
                             }
                             """);

            return new KeyValuePair<string, string>($"{typeName}BuilderExtensions.g.cs", stringBuilder.ToString());
        }
        finally
        {
            stringBuilderPool.Return(stringBuilder);
        }
    }

    private static void GenerateBuilderMethod(ITypeSymbol type, ImmutableHashSet<ITypeSymbol> types, IPropertySymbol property, StringBuilder stringBuilder)
    {
        string typeName = type.Name;
        string propertyName = property.Name;
        string propertyType = property.Type.ToDisplayString();

        stringBuilder.Append("        public static Builder<");
        stringBuilder.Append(typeName);
        stringBuilder.Append("> With");
        stringBuilder.Append(propertyName);
        stringBuilder.Append("(this Builder<");
        stringBuilder.Append(typeName);
        stringBuilder.Append("> builder, ");
        stringBuilder.Append(propertyType);
        stringBuilder.AppendLine(" value) ");
        if (type.IsRecord)
        {
            stringBuilder.Append("            => builder.Apply(obj => obj with { ");
            stringBuilder.Append(propertyName);
            stringBuilder.AppendLine(" = value });");
        }
        else
        {
            stringBuilder.Append("            => builder.Apply(obj => obj.");
            stringBuilder.Append(propertyName);
            stringBuilder.AppendLine(" = value);");
        }

        if (!types.Contains(property.Type))
        {
            return;
        }

        stringBuilder.Append("        public static Builder<");
        stringBuilder.Append(typeName);
        stringBuilder.Append("> With");
        stringBuilder.Append(propertyName);
        stringBuilder.Append("(this Builder<");
        stringBuilder.Append(typeName);
        stringBuilder.Append("> builder, Func<Builder<");
        stringBuilder.Append(propertyType);
        stringBuilder.Append(">, Builder<");
        stringBuilder.Append(propertyType);
        stringBuilder.AppendLine(">> action) ");
        if (type.IsRecord)
        {
            stringBuilder.Append("            => builder.Apply(obj => obj with { ");
            stringBuilder.Append(propertyName);
            stringBuilder.Append(" = action(Builder.Create<");
            stringBuilder.Append(propertyType);
            stringBuilder.AppendLine(">()).Build() });");
        }
        else
        {
            stringBuilder.Append("            => builder.Apply(obj => obj.");
            stringBuilder.Append(propertyName);
            stringBuilder.Append(" = action(Builder.Create<");
            stringBuilder.Append(propertyType);
            stringBuilder.AppendLine(">()).Build());");
        }
    }
}